-- MySQL Script generated by MySQL Workbench
-- Wed Dec 12 17:27:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dutinfopw201623
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dutinfopw201623` ;

-- -----------------------------------------------------
-- Schema dutinfopw201623
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dutinfopw201623` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `dutinfopw201623` ;

-- -----------------------------------------------------
-- Table `dutinfopw201623`.`commenter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dutinfopw201623`.`commenter` (
  `idUtilisateur` BIGINT(20) NOT NULL,
  `idTrajet` BIGINT(20) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `idAuteur` BIGINT(20) NOT NULL,
  `date` DATE NOT NULL,
  `note` SMALLINT(6) NOT NULL,
  PRIMARY KEY (`idUtilisateur`, `idTrajet`),
  UNIQUE INDEX `idAuteur_UNIQUE` (`idAuteur` ASC),
  INDEX `fk_utilisateur_has_trajet_trajet1_idx` (`idTrajet` ASC),
  INDEX `fk_utilisateur_has_trajet_utilisateur1_idx` (`idUtilisateur` ASC),
  CONSTRAINT `fk_utilisateur_has_trajet_trajet1`
    FOREIGN KEY (`idTrajet`)
    REFERENCES `dutinfopw201623`.`trajet` (`idTrajet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_trajet_utilisateur1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `dutinfopw201623`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `dutinfopw201623`.`discussion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dutinfopw201623`.`discussion` (
  `idDiscussion` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `idUtilisateur1` BIGINT(20) NOT NULL,
  `idUtilisateur2` BIGINT(20) NOT NULL,
  `contenuMessage` VARCHAR(255) NOT NULL,
  `idUtilisateurParle` BIGINT(20) NOT NULL,
  `date` DATE NOT NULL,
  `lu` TINYINT(4) NOT NULL,
  PRIMARY KEY (`idDiscussion`, `idUtilisateur1`, `idUtilisateur2`),
  UNIQUE INDEX `idDiscussion_UNIQUE` (`idDiscussion` ASC),
  INDEX `fk_utilisateur_has_utilisateur_utilisateur2_idx` (`idUtilisateur2` ASC),
  INDEX `fk_utilisateur_has_utilisateur_utilisateur1_idx` (`idUtilisateur1` ASC),
  CONSTRAINT `fk_utilisateur_has_utilisateur_utilisateur1`
    FOREIGN KEY (`idUtilisateur1`)
    REFERENCES `dutinfopw201623`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_utilisateur_utilisateur2`
    FOREIGN KEY (`idUtilisateur2`)
    REFERENCES `dutinfopw201623`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `dutinfopw201623`.`favoris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dutinfopw201623`.`favoris` (
  `idfavoris` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `idUtilisateur` BIGINT(20) NOT NULL,
  `requete` VARCHAR(255) NOT NULL,
  `nom` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`idfavoris`),
  UNIQUE INDEX `idfavoris_UNIQUE` (`idfavoris` ASC),
  INDEX `fk_favoris_utilisateur1_idx` (`idUtilisateur` ASC),
  CONSTRAINT `fk_favoris_utilisateur1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `dutinfopw201623`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `dutinfopw201623`.`soustrajet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dutinfopw201623`.`soustrajet` (
  `idsousTrajet` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `idTrajet` BIGINT(20) NOT NULL,
  `dateDepart` DATE NOT NULL,
  `heureDepart` TIME NOT NULL,
  `idVilleDepart` BIGINT(20) NOT NULL,
  `idVilleArrivee` BIGINT(20) NOT NULL,
  `heureArrivee` TIME NOT NULL,
  `idVehiculeConducteur` BIGINT(20) NOT NULL,
  `prix` FLOAT NOT NULL,
  `prixCumule` FLOAT NOT NULL,
  `regulier` TINYINT(4) NOT NULL,
  PRIMARY KEY (`idsousTrajet`),
  UNIQUE INDEX `idsousTrajet_UNIQUE` (`idsousTrajet` ASC),
  INDEX `fk_sousTrajet_trajet1_idx` (`idTrajet` ASC),
  CONSTRAINT `fk_sousTrajet_trajet1`
    FOREIGN KEY (`idTrajet`)
    REFERENCES `dutinfopw201623`.`trajet` (`idTrajet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `dutinfopw201623`.`soustrajetutilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dutinfopw201623`.`soustrajetutilisateur` (
  `utilisateur_idutilisateur` BIGINT(20) NOT NULL,
  `sousTrajet_idsousTrajet` BIGINT(20) NOT NULL,
  `valide` TINYINT(4) NOT NULL,
  `prixPayer` FLOAT NOT NULL,
  PRIMARY KEY (`utilisateur_idutilisateur`, `sousTrajet_idsousTrajet`),
  INDEX `fk_utilisateur_has_sousTrajet_sousTrajet1_idx` (`sousTrajet_idsousTrajet` ASC),
  INDEX `fk_utilisateur_has_sousTrajet_utilisateur1_idx` (`utilisateur_idutilisateur` ASC),
  CONSTRAINT `fk_utilisateur_has_sousTrajet_sousTrajet1`
    FOREIGN KEY (`sousTrajet_idsousTrajet`)
    REFERENCES `dutinfopw201623`.`soustrajet` (`idsousTrajet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_sousTrajet_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur`)
    REFERENCES `dutinfopw201623`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `dutinfopw201623`.`trajet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dutinfopw201623`.`trajet` (
  `idTrajet` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descriptionTrajet` VARCHAR(1023) NULL DEFAULT NULL,
  `idConducteur` BIGINT(20) NOT NULL,
  `placeTotale` SMALLINT(6) NOT NULL DEFAULT '0',
  `suppression` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idTrajet`),
  UNIQUE INDEX `idTrajet_UNIQUE` (`idTrajet` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `dutinfopw201623`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dutinfopw201623`.`utilisateur` (
  `idUtilisateur` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(32) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `motDePasse` VARCHAR(255) NOT NULL,
  `dateDeNaissance` DATE NULL DEFAULT NULL,
  `sexe` TINYINT(4) NULL DEFAULT NULL,
  `adresseMail` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `urlPhoto` VARCHAR(128) NULL DEFAULT NULL,
  `credit` FLOAT NOT NULL DEFAULT '0',
  `dateCreation` DATE NOT NULL,
  `token` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`idUtilisateur`),
  UNIQUE INDEX `adresseMail_UNIQUE` (`adresseMail` ASC),
  UNIQUE INDEX `idutilisateur_UNIQUE` (`idUtilisateur` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `dutinfopw201623`.`vehicule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dutinfopw201623`.`vehicule` (
  `immatriculation` VARCHAR(32) NOT NULL,
  `hybride` TINYINT(4) NOT NULL,
  `critair` INT(11) NOT NULL,
  `urlPhoto` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`immatriculation`),
  UNIQUE INDEX `immatriculation_UNIQUE` (`immatriculation` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `dutinfopw201623`.`vehiculeutilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dutinfopw201623`.`vehiculeutilisateur` (
  `idUtilisateur` BIGINT(20) NOT NULL,
  `immatriculation` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idUtilisateur`, `immatriculation`),
  INDEX `fk_utilisateur_has_vehicule_vehicule1_idx` (`immatriculation` ASC),
  INDEX `fk_utilisateur_has_vehicule_utilisateur1_idx` (`idUtilisateur` ASC),
  CONSTRAINT `fk_utilisateur_has_vehicule_utilisateur1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `dutinfopw201623`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_vehicule_vehicule1`
    FOREIGN KEY (`immatriculation`)
    REFERENCES `dutinfopw201623`.`vehicule` (`immatriculation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `dutinfopw201623`.`ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dutinfopw201623`.`ville` (
  `idVille` INT(5) NULL DEFAULT NULL,
  `nomVille` VARCHAR(26) NULL DEFAULT NULL,
  `codePostal` INT(5) NULL DEFAULT NULL,
  `LIBELLE D'ACHEMINEMENT` VARCHAR(26) NULL DEFAULT NULL,
  `Y_CENTROID` INT(5) NULL DEFAULT NULL,
  `NOM_REGION` VARCHAR(13) NULL DEFAULT NULL,
  `NOM_DEPT` VARCHAR(17) NULL DEFAULT NULL,
  `STATUT` VARCHAR(16) NULL DEFAULT NULL,
  `CODE_REG` INT(2) NULL DEFAULT NULL,
  `CODE_COMM` INT(3) NULL DEFAULT NULL,
  `Z_MOYEN` INT(3) NULL DEFAULT NULL,
  `CODE_DEPT` INT(2) NULL DEFAULT NULL,
  `Geo Point` VARCHAR(28) NULL DEFAULT NULL,
  `X_CENTROID` INT(4) NULL DEFAULT NULL,
  `ID_GEOFLA` INT(5) NULL DEFAULT NULL,
  `X_CHF_LIEU` INT(4) NULL DEFAULT NULL,
  `CODE_CANT` INT(2) NULL DEFAULT NULL,
  `Geo Shape` VARCHAR(1730) NULL DEFAULT NULL,
  `SUPERFICIE` INT(5) NULL DEFAULT NULL,
  `POPULATION` DECIMAL(6,1) NULL DEFAULT NULL,
  `NOM_COMM` VARCHAR(28) NULL DEFAULT NULL,
  `CODE_ARR` INT(1) NULL DEFAULT NULL,
  `Y_CHF_LIEU` INT(5) NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
